spring:
  datasource:
    url: ${URL_DATASOURCE}
    username: ${USERNAME_DATASOURCE}
    password: ${PASSWORD_DATASOURCE}

  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
      roles: ${SECURITY_USER_ROLE}

  springdoc:
    api-docs.path: ${SWAGGER_PATH}
    swagger-ui:
      path: ${SWAGGER_UI_PATH}
      operations-sorter: ${SWAGGER_UI_OPERATIONS}
      tags-sorter: ${SWAGGER_UI_TAGS}
      doc-expansion: ${SWAGGER_UI_EXPANSION}
      display-request-duration: ${SWAGGER_UI_REQUEST_DURATION}
      default-model-expand-depth: ${SWAGGER_UI_DEFAULT_MODEL}
      show-extensions: ${SWAGGER_SHOW_EXTENSIONS}
      show-common-extensions: ${SWAGGER_COMMUN_EXTENSIONS}
    override-with-generic-response: false
    model-converters:
      pageable-converter:
        enabled: false

api:
  security:
    token:
      secret: ${TOKEN_KEY}