spring:
  datasource:
    url: ${URL_DATASOURCE}
    username: ${USERNAME_DATASOURCE}
    password: ${PASSWORD_DATASOURCE}

  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
      roles: ${SECURITY_USER_ROLE}

  springdoc:
    api-docs.path: ${SWAGGER_PATH}
    swagger-ui:
      path: ${SWAGGER_UI_PATH}
      operations-sorter: ${SWAGGER_UI_OPERATIONS}
      tags-sorter: ${SWAGGER_UI_TAGS}
      doc-expansion: ${SWAGGER_UI_EXPANSION}
      display-request-duration: ${SWAGGER_UI_REQUEST_DURATION}
      default-model-expand-depth: ${SWAGGER_UI_DEFAULT_MODEL}
      show-extensions: ${SWAGGER_SHOW_EXTENSIONS}
      show-common-extensions: ${SWAGGER_COMMUN_EXTENSIONS}
    override-with-generic-response: false
    model-converters:
      pageable-converter:
        enabled: false

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    test-connection: false

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

api:
  security:
    token:
      secret: ${TOKEN_KEY}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  telefone: ${ADMIN_TELEFONE:11999999999}
