spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=password

# JWT Secret - Mínimo 32 caracteres
api.security.token.secret=minha-chave-super-secreta-senhor-que-grande

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN